const SET_ACCESSTOKEN = 'SET_ACCESSTOKEN'
const SET_TIMESTAMP = 'SET_TIMESTAMP'
const SET_USERINFO = 'SET_USERINFO'
const SET_SCHOOLNAME = 'SET_SCHOOLNAME'
const SET_SUBMIT = 'SET_SUBMIT'
export {
  SET_ACCESSTOKEN,
  SET_TIMESTAMP,
  SET_USERINFO,
  SET_SCHOOLNAME,
  SET_SUBMIT
}